### ISSUE TITLE
UI crashes during import (Unhandled Runtime Error)

### ISSUE THREAD

**Issue by Sven-Lyco** [Luzefiru/wuwatracker#35]
# Bug Description

When clicking on Import to import the history, the application crashes

## How to Reproduce

_A reproduction repository is greatly appreciated._

1. Go to 'http://localhost:3000/import'
2. Copy installation folder "D:\Wuthering Waves\Wuthering Waves Game" ( in my case)
3. Copy and execute the script for Powershell in Windows Powershell
4. Copy the give URL into step 3.
5. Click on 'Import History'
6. See error

## Expected Behavior

The UI does not crash and the import is successful

### import Site
![grafik](https://github.com/Luzefiru/wuwatracker/assets/98020906/0c8bb61e-a4f5-4d75-a196-ecdcf6203561)

### ERROR
![grafik](https://github.com/Luzefiru/wuwatracker/assets/98020906/52953cd1-a085-429f-83db-aa6edf8cc3fa)
![grafik](https://github.com/Luzefiru/wuwatracker/assets/98020906/fdf9f7f3-f330-4e09-98d6-0c60134284c5)
![grafik](https://github.com/Luzefiru/wuwatracker/assets/98020906/d7297fb3-9a47-4cbd-83c8-6e65b13fdea2)
![grafik](https://github.com/Luzefiru/wuwatracker/assets/98020906/ba216ef5-307c-4901-906d-5240e05ec140)

## Platform/OS

_Desktop (please complete the following information):_

- OS: Windows 11 (23H2)
- Browser: Firefox Developer Edition & Chrome 
- Version: 127.0b9 (64-bit) & 125.0.6422.141

**Comment by Sven-Lyco** [comment]
Okay, I should have read better.
I have customized the `LanguageCode` in `src/types/LangaugeCode.ts` :

```typescript
import { z } from "zod";

export const LanguageCode = {
  de: "de",
} as const;
export const LanguageCodeEnumSchema = z.nativeEnum(LanguageCode);
export type LangaugeCodeEnum = z.infer<typeof LanguageCodeEnumSchema>;
```

And now it works. Maybe it would be an improvement to give a hint about the language settings or the possibility to change the language

**Comment by Luzefiru** [comment]
This is a good find. The history URL has a `languageCode` property which I naively set to only allow `"en"`. 

It might be worth considering to remove the reliance of `languageCode` by:
- removing it from the data schema & the functions that use it/extract it
- just hard coding `languageCode: "en"` to all requests, see [useConveneHistory's getHistoryByCardPoolType method](https://github.com/Luzefiru/wuwatracker/blob/main/src/hooks/useConveneHistory.ts)

We do not have a reliable way to display localized language results at the moment since we hard code a lot of English values for comparison, so I think its best to make this website English only for now until we find a better way.

Is that a workable solution? Regardless, I'd love help in resolving this.

**Comment by Sven-Lyco** [comment]
> This is a good find. The history URL has a `languageCode` property which I naively set to only allow `"en"`.
> 
> It might be worth considering to remove the reliance of `languageCode` by:
> 
>     * removing it from the data schema & the functions that use it/extract it
> 
>     * just hard coding `languageCode: "en"` to all requests, see [useConveneHistory's getHistoryByCardPoolType method](https://github.com/Luzefiru/wuwatracker/blob/main/src/hooks/useConveneHistory.ts)
> 
> 
> We do not have a reliable way to display localized language results at the moment since we hard code a lot of English values for comparison, so it's best to make this website English only for now until we find a better way.
> 
> Is that a workable solution? Regardless, I'd love your help in resolving this, @Sven-Lyco.

I forked your project and will try a different things, but it will take time

**Comment by Luzefiru** [comment]
> I forked your project and will try a different things, but it will take time

Sure thing! I'm looking forward to what other methods you'll find to help support other languages. I'll merge the temporary fix for now since it's affecting users at the moment.

Will close this issue now since it [works on your machine now](https://github.com/Luzefiru/wuwatracker/pull/38#issuecomment-2146979073).
