### ISSUE TITLE
iOS suport

### ISSUE THREAD

**Issue by Yana-Kuz** [Luzefiru/wuwatracker#49]
# Problem

There is no iOS support like on paimon moe. I know that android is very hard to implement, but on iOS you could get "GET POST" URL and get convene from JSON.

## Possible Solution

After getting JSON it is easy to have the convene history. URL could be get via App Stream in AppStore

**Comment by Luzefiru** [comment]
I agree. Mobile support is possible in theory since the game (in PC at least), sends an HTTP GET request to their public API with all the data in the query params.

If someone with Android or iOS experience can help us by suggesting a method to pinpoint the URL that fetches the data, it would help us make implement this feature.

**Comment by Luzefiru** [comment]
@Yana-Kuz, have you tried using [paimon.moe's iOS import method](https://paimon.moe/wish/import) with Wuthering Waves? The URLs should start with:
- https://aki-gm-resources-oversea.aki-game.net
- https://aki-gm-resources-oversea.aki-game.com

**Comment by Luzefiru** [comment]
Closing this issue in the meantime since we've added a tutorial to the website for a good amount of time without any issues.
