### ISSUE TITLE
Global scrollbar

### ISSUE THREAD

**Issue by Iftuga** [Luzefiru/wuwatracker#86]
Hello there, love the website, but one nitpick from me

There is a global scrollbar that is always there even when everything fits, for example in the settings and import pages there is a lot of empty space on most desktop resolutions but the scrollbar is still there and it does not feel right

**Comment by Luzefiru** [comment]
Yeah, this was something we tried to fix before, but didn't find a proper way to do it without messing with the other parts of the layout. We'll keep this in the back burner for now while we focus on other features with higher priority.

But thank you for opening an issue about it @Iftuga! GitHub has the highest visibility for issues, so I'm really glad you placed it here. 😅

**Comment by Luzefiru** [comment]
We adjusted the spacing on the layout now. How does it look on your end, @Iftuga?

**Comment by Luzefiru** [comment]
> like in the pull history, but for banner types, achievement categories, etc., but that is just a preference

You're not the only one, and we agree! A lot of people have been asking for scrollbars or something to indicate that it's scrollable.

We'll be prioritizing this soon since we're doing batches of UX touch-ups at the moment, so stay tuned. 😉

I'll be closing this issue for now since we've fixed the main issue with the global scrollbars, but feel free to reopen it if you catch something else! 👍
